# Generated by Django 3.2.3 on 2021-06-06 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_job_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='status',
            new_name='job_active',
        ),
    ]
