# Generated by Django 3.2.3 on 2021-06-06 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0004_rename_status_job_job_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='Linkedin_Profile',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
