# Generated by Django 3.2.3 on 2021-06-06 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0005_alter_candidate_linkedin_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='Expected_hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='Years_of_Experience',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=1, null=True),
        ),
    ]
